### PR TITLE
Get rid of @string/@int for polyvars

### LINKED ISSUE #748: Replace poly variants that use @as with strings
## The problem

When using poly variants for string enums, we transformed a lot of "string-with-dash" to camel case stringWithoutDash, relying on ReScript `@as` annotation.
Now that ReScript allows poly variants to have string syntax, we could  change this choice to make it more straight forward to new ReScript user that are familiar with React Native.

## Considered solution

We could make this a breaking change. Maybe a codemod will help.

## Alternatives solutions

We can also:

* add strings values (so people can use both syntax (with-dash or withoutDash) and keep both (maintenance++)
* integrate both & deprecate later withoutDash if that possible (syntax seems to be accepted but it doesn't seems to show the warning - I tested  `| @deprecated("use #\"plain-text\" instead of #plainText") @as("plain-text") #plainText` in `Alert.res`)

### PR DESCRIPTION
**Pull request by cknitt**
Closes #748.

These are breaking changes, but I think that's ok - more breaking changes likely to come with #766.

### CODE REVIEW

**Review by MoOx — APPROVED** [review]
Awesome ! Thanks for spending time on this!

**Comment by cknitt** [comment]
Just noticed I had forgotten the `=?` in
```rescript
  ~pointerEvents: pointerEvents=?,
```
in a few places. Updated the PR.

**Comment by MoOx** [comment]
@cknitt  Could you reopen this PR (create a new one yourself so you get proper credit) ? https://github.com/rescript-react-native/rescript-react-native/compare/main...simplify-polyvars?expand=1

**Comment by cknitt** [comment]
Done, thanks!

**Pull request merged**
