### PR TITLE
Add binding for Platform.Version

### PR DESCRIPTION
**Pull request by tienle**
Detects the version of the platform in which the app is running.

https://reactnative.dev/docs/platform-specific-code#detecting-the-android-version

### CODE REVIEW

**Comment by cknitt** [comment]
According to the docs you linked, `Platform.Version` is a string for iOS, but an int for Android. This should be reflected correctly in the bindings IMHO.

One way to do this might be to have both

* `Platform.iosVersion` (string) and
* `Platform.androidVersionCode` (int)

?

**Comment by cknitt** [comment]
LGTM - what do you think, @MoOx?

**Comment by MoOx** [comment]
For better discoverability (autocomplete), I would call them `.versionIos` & `.versionAndroid`

**Comment by cknitt** [comment]
@MoOx Another idea:

Looking at the TypeScript definitions, I noticed that there is some other OS-specific information (isPad, isTVOS).

So maybe we should have Platform.IOS.version (string), Platform.IOS.isPad, Platform.IOS.isTVOS and Platform.Android.version (int)?

**Comment by MoOx** [comment]
@cknitt I would prefer to be close to original API without adding any complexity for new comers.
@sgny anything to add to help us with this decision ? 😁

**Comment by sgny** [comment]
`Platform.constants` returns quite a bit of information, including some which may be useful, such as the RN version, fingerprint for Android, etc. Set of available keys seems rather different between iOS and Android. We could support access to that directly which should handle other functionality as well. For example, `isPad` and `isTV` (`isTVOS` is deprecated) are simply whether `interfaceIdiom` key is `"tv"` or `"pad"`.

**Comment by MoOx** [comment]
Ok so you recommend that we bind Platform.constants instead of Platform.versionX ?

**Comment by MoOx** [comment]
@sgny up for my question :)

**Comment by MoOx** [comment]
@tuanmai up :)

**Pull request closed without merging**
