### PR TITLE
Js.Dict.t -> dict

### PR DESCRIPTION
**Pull request by cknitt**

### CODE REVIEW

**Comment by Freddy03h** [comment]
You want to remove all ref to `Js` module before the `0.75` release?

**Comment by cknitt** [comment]
Where possible, yes.
There may be some follow-up PRs. 🙂

**Comment by Freddy03h** [comment]
Ok, and you also want to add `Core` ?

**Review by Freddy03h — APPROVED** [review]

**Comment by cknitt** [comment]
No, this would be hard, because right now it is an extra dependency, but in v12 it will be part of the `rescript` npm package.

**Pull request merged**
